services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:

      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
      POSTGRES_DB: training
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
